import {filterPlaces,parseIntent} from './logic.mjs';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data=null;
const presets={focus:'想专注工作一小时，最多步行15分钟，插座只是偏好',rest:'想放空休息一会儿，最多步行10分钟',strict:'想专注工作一小时，最多步行15分钟，必须有插座'};
fetch('./data.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(x=>data=x).catch(()=>{$('.home-note').textContent='案例数据未能加载，请刷新重试。';$('#start').disabled=true;});
const settings=()=>({minutes:Number($('#minutes').value),budget:Number($('#budget').value),outlets:$('#outlets').checked});
function city(){const s=$('#city');$('#city-art').src=`./assets/${s.value}.webp`;$('#city-art').alt=`${s.selectedOptions[0].text}水彩城市插画，非导航地图`;$('#city-name').textContent=s.selectedOptions[0].text;}
function home(){document.body.classList.remove('working');$('#home').hidden=false;$('#workspace').hidden=true;window.scrollTo(0,0);}
function render(){if(!data)return;const s=settings(),places=filterPlaces(data.places,s);$('#minutes-label').textContent=`${s.minutes} 分钟`;$('#result-title').textContent=places.length?`这次，可以看看这 ${places.length} 处`:'这次，先不急着推荐';$('#result-note').textContent=s.outlets?'样本没有可核实的插座信息，不能确认满足你的必须条件。':`从利西路102号出发 · 步行不超过 ${s.minutes} 分钟 · 按真实路线耗时排序`;$('#result-list').innerHTML=places.length?places.map((p,i)=>`<article class="place"><div class="place-title"><span class="number">${String(i+1).padStart(2,'0')}</span><h3><button data-place="${esc(p.baidu_uid)}">${esc(p.name)}</button></h3></div><p class="address">${esc(p.address)}</p><div class="place-meta"><span>步行约 ${Math.ceil(p.route.duration_seconds/60)} 分钟 · ${p.route.distance_meters} 米</span>${p.reference_price===null?'':`<span>参考 ¥${p.reference_price}</span>`}</div><p class="reason">${i===0?'本轮候选中步行最省时，可以少花一点时间在路上。':'在你愿意走的范围内，可以作为另一个选择。'}</p><div class="place-bottom"><span>${$('#purpose').value==='chat'?'交谈环境':$('#purpose').value==='rest'?'噪声与拥挤程度':'安静程度、插座与座位'}尚未核实</span><button data-place="${esc(p.baidu_uid)}">为什么选它 ↗</button></div></article>`).join(''):`<div class="empty"><strong>${s.outlets?'没有证据，也是一种答案。':'这次的范围里，还没有合适结果。'}</strong>${s.outlets?'百度地点字段与已有评论样本都不能确认插座。你可以保留要求，或主动将它改为偏好。':'尝试增加步行时间，或调整参考预算。'}<button id="relax">${s.outlets?'将插座改为偏好，再看看':'恢复 15 分钟、不限预算'}</button></div>`;$('#relax')?.addEventListener('click',()=>{$('#outlets').checked=false;if(!s.outlets){$('#minutes').value=15;$('#budget').value=999;}render();});}
function start(text=''){if(!data){$('.home-note').textContent='正在加载公开案例，请稍后再试。';return;}const parsed=parseIntent(text);$('#purpose').value=parsed.purpose;$('#minutes').value=parsed.minutes;$('#outlets').checked=parsed.outlets;$('#budget').value=999;$('#intent-note').textContent=text?'已按演示规则填入条件，请核对。任意复杂需求需使用完整项目的在线 AI。':'筛选在本地完成，演示版不调用在线 AI。';$('#city').value='shanghai';city();$('#home').hidden=true;$('#workspace').hidden=false;document.body.classList.add('working');render();window.scrollTo(0,0);$('#purpose').focus({preventScroll:true});}
$('#start').onclick=()=>start();$('#intent-form').onsubmit=e=>{e.preventDefault();start($('#intent').value)};document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{const text=presets[b.dataset.preset];$('#intent').value=text;start(text)});
$('#city').onchange=()=>{city();home()};$('#home-button').onclick=home;$('#back').onclick=home;$('#theme').onclick=()=>{const dark=document.body.classList.toggle('dark');$('#theme').textContent=dark?'☾':'☼';$('#theme').setAttribute('aria-label',dark?'切换日间模式':'切换夜间模式')};$('#about').onclick=()=>$('#method').showModal();document.querySelectorAll('dialog .close').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));
$('#minutes').oninput=render;$('#budget').onchange=render;$('#outlets').onchange=render;$('#purpose').onchange=render;$('#apply').onclick=render;
function detail(uid){const p=data.places.find(x=>x.baidu_uid===uid);if(!p)return;$('#detail-content').innerHTML=`<p class="eyebrow">百度地图 / 地点与路线回放</p><h2>${esc(p.name)}</h2><p class="muted">${esc(p.address)}</p><div class="fact-grid"><div><small>百度步行路线</small>${Math.ceil(p.route.duration_seconds/60)} 分钟 / ${p.route.distance_meters} 米</div><div><small>参考人均</small>${p.reference_price===null?'未知':`¥${p.reference_price}`}</div><div><small>登记营业时间</small>${esc(p.opening_hours_text??'未提供')}</div><div><small>地图评分 / 评论计数</small>${esc(p.overall_rating??'未知')} / ${esc(p.provider_comment_count??'未知')}</div></div><h3>这次推荐的依据</h3><p>百度步行路线耗时在你设定的 ${settings().minutes} 分钟内${settings().budget<999?'，参考价格也在预算内':''}。这里按地图字段提供候选，尚不能判断是否适合${$('#purpose').selectedOptions[0].text}。</p><p class="caution">本店没有纳入可读评论正文。评论计数不等于已读评论，不据此生成环境结论。当前座位、插座与噪声仍未知。</p><p class="muted">采集于 2026-09-29。此页为真实接口数据回放，非当前路线或营业保证。</p><div class="dialog-actions"><a href="${esc(p.source_url)}" target="_blank" rel="noopener noreferrer">到百度地图查看 ↗</a><button id="other-evidence">看另一家店的评论分析示例 →</button></div>`;$('#other-evidence').onclick=()=>review(0);if(!$('#detail').open)$('#detail').showModal();}
$('#result-list').onclick=e=>{const b=e.target.closest('[data-place]');if(b)detail(b.dataset.place)};
function review(index=0){if(!data)return;const r=data.reviews[index],quote=r.reviews[0];$('#detail-content').innerHTML=`<p class="eyebrow">独立评论案例 / 预先整理的解读</p><h2>一句评论，能说明多少？</h2><div class="review-tabs"><button data-review="0" aria-pressed="${index===0}">有相关线索</button><button data-review="1" aria-pressed="${index===1}">证据不足</button></div><h3>${esc(r.name)}</h3><p class="muted">${esc(r.totalLabel)} · 实际可读 1 条 · 与上方附近地点列表为独立样本</p><blockquote>“${esc(quote.text)}”<cite>${esc(quote.date)} · 百度地图历史评论 · 2026-09-29 读取</cite></blockquote><h3>${index===0?'可以保留一条线索':'提问，不是事实'}</h3><p>${index===0?'“适合学习，工作，开会”提供了与工作场景相关的历史观察，值得进一步确认。但只有一条可读评论，且发表于 2023 年，不能推出今天仍然安静、可以久坐或有插座。':'“几点开始营业”是在提问，没有提供营业时间，更没有提供安静、座位或插座的事实。不能把这个问题当成环境推荐依据。'}</p><p class="caution">${index===0?'演示判断：可以作为环境线索；不能证明任何必须条件已满足。':'演示判断：与本次工作需求相关的有效样本为 0，保留未知，不强行推荐。'}</p><p class="muted">这是固定样本的解读演示，不是在线 AI 输出。完整项目将同店原文与引用核对后展示；历史评论与现实状态始终分开。</p><a href="https://map.baidu.com/?qt=inf&uid=${esc(r.uid)}" target="_blank" rel="noopener noreferrer">在百度地图查看这家店 ↗</a>`;document.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>review(Number(b.dataset.review)));if(!$('#detail').open)$('#detail').showModal();}
$('#review-demo').onclick=()=>review();$('#evidence-open').onclick=()=>review();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'configure_quietlens_demo',description:'Start the Shanghai recorded-data demo and filter recorded places. Does not make a live map or AI request.',inputSchema:{type:'object',properties:{minutes:{type:'number',minimum:1,maximum:20},outlets:{type:'boolean'}},required:['minutes','outlets'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input){if(!data)throw Error('Data not ready');filterPlaces(data.places,{minutes:input.minutes,budget:999,outlets:input.outlets});start();$('#minutes').value=input.minutes;$('#outlets').checked=input.outlets;render();return {mode:'recorded_demo',fetched_at:data.fetched_at,places:filterPlaces(data.places,settings()).map(p=>p.name)};}})).catch(()=>{});}catch{}}
